services:

  smm:
    build: .
    container_name: smm_automator
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
      RAPIDAPI_HOST: ${RAPIDAPI_HOST}
      MORETHANPANEL_API_KEY: ${MORETHANPANEL_API_KEY}
      MORETHANPANEL_URL: ${MORETHANPANEL_URL}
      TZ: ${TZ:-America/Sao_Paulo}
